name: "SCRYVEX PRO"
version: "1.0.0"
url: "https://github.com/Chrisalvir1/Scryvex-Pro"
slug: "scryvex_pro"
description: "Zero-Latency Local-First NVR con YOLOv10 y Matter 1.6"
arch:
  - aarch64
init: false
host_network: true
map:
  - config:rw
  - data:rw
ports:
  9090/tcp: 9090
  4000/udp: 4000
  55600/tcp: 55600
ports_description:
  9090/tcp: "Liquid Glass UI Web Interface"
  4000/udp: "WebRTC HKSV Port"
  55600/tcp: "Red Matter Base Port"
