#!/command/with-contenv bash
until su - postgres -c "pg_isready -q"; do sleep 1; done
su - postgres -c "psql -tc \"SELECT 1 FROM pg_database WHERE datname = 'scryvex_core'\" | grep -q 1 || psql -c \"CREATE DATABASE scryvex_core\""
su - postgres -c "psql -tc \"SELECT 1 FROM pg_roles WHERE rolname = 'scryvex'\" | grep -q 1 || psql -c \"CREATE USER scryvex WITH PASSWORD 'scryvex'\""
su - postgres -c "psql -c \"GRANT ALL PRIVILEGES ON DATABASE scryvex_core TO scryvex\""
su - postgres -c "psql -d scryvex_core -c \"GRANT ALL ON SCHEMA public TO scryvex\""
